### ISSUE TITLE
封装一个github的api

### ISSUE THREAD

**Issue by agassiyzh** [sixuanhan/with-yzh#10]
现在已经知道了怎么写spring的api，和请求第三方的API。
现在我们来完整自己实现一遍这个流程。

新建一个spring boot项目。

写一个api 列出`sixuanhan/with-yzh` 这个项目所有状态为open的issues。

github api 参考：https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues

**Comment by agassiyzh** [comment]
```java
  @GetMapping("/quote")
    public Object quote(RestTemplate restTemplate, @RequestParam(value = "name", defaultValue = "Dandan" +
            "") String name) {
              Object getQuote = restTemplate.getForObject(
                "https://api.github.com/repos/sixuanhan/with-yzh/issues", Object.class);
    
    return getQuote;
  };
```

**Comment by agassiyzh** [comment]
https://www.baeldung.com/rest-template

这里有RestTemplate的介绍，可以看看如何设置header

**Comment by agassiyzh** [comment]
这个先别关，我看看Header怎么给你整明白

**Comment by agassiyzh** [comment]
看一下第一条回答，和它的评论：https://stackoverflow.com/questions/16781680/http-get-with-headers-using-resttemplate

**Comment by sixuanhan** [comment]
明白了。我试了一下，虽然不确定header有没有加上去，但是看起来都非常成功
